### ISSUE TITLE
Consistently named internal nodes

### ISSUE THREAD

**Issue by luisacusick** [veidenberg/wasabi#21]
Is there a way to run prank using the -showanc option and generate ancestral alignments that have consistent numbering? For example, if one alignment is missing a few species is there a way to ensure that the number given to an inferred ancestral sequences will match up with numbers given to inferred ancestral sequences when there are no missing species? Thank you!

**Comment by ariloytynoja** [comment]
I'm afraid that this feature is unlikely to be implemented in the near future.

The node numbering has to be based on some rule and in PRANK it is defined by the visiting order while recursively going through the tree. It used to be possible to define a guidetree with node labels but this was implemented to get around a bug in BppAncestor and the functionality has since been removed. 

A possible hack to get a similar result would be insert a minimal placeholder for the missing species. If the data are DNA, the missing  sequence could be one 'N'; if they are proteins, the sequence could be one 'X'. If there are lots of missing species, such fake sequences will probably affect the alignment and should not be used. In that case, one could consider adding the fake sequences (with appropriate padding with gap signs) after the first alignment and then rerunning PRANK with option "-keep" to reconstruct the ancestral sequences. It is possible that the reconstructed gap pattern is affected by the fake sequences and the correct behaviour cannot be guaranteed.
