### ISSUE TITLE
How is https support by Wasabi?

### ISSUE THREAD

**Issue by smoretti** [veidenberg/wasabi#3]
For what I look in the javascript code I wonder how is the https support in wasabi?

**Comment by veidenberg** [comment]
Hi,

I have not implemented https in Wasabi.
Data security currently relies on the random string access keys tied with user accounts and datasets.
Https support is a planned feature, although will probably be using a self-signed certificate on wasabiapp.org because of cost restrictions.

Regards,

Andres

-------
Andres Veidenberg
PhD student (Löytynoja lab)
Institute of Biotechnology
University of Helsinki, Finland
http://wasabiapp.org

**Comment by smoretti** [comment]
OK, thanks
